<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Tuesday 18th of March 2014 07:48:03 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://hybcms.vs/HybridCMS/Modules/Hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "25767675371-igptnv1c53dktc6uo6g4e0eq21ocfrar.apps.googleusercontent.com", "secret" => "0lHyBXcDbWxFPQJ5c5h1x1g-" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "525834434195795", "secret" => "40909b418377eb3d057afa759dc07557" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "fBSENWkwzVUOMCmEGscwQ", "secret" => "pK4SHOiRucipuCUaoIoP13Jk03OIL0LlcoycYMy8E" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
